apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  TWILIO_ACCOUNT_SID:   {{ .Values.twilio.accountSid | quote }}
  TWILIO_AUTH_TOKEN:    {{ .Values.twilio.authToken | quote }}
  TWILIO_WHATSAPP_FROM: {{ .Values.twilio.whatsappFrom | quote }}
