"""create alerts table

Revision ID: 887d198373fc
Revises: 
Create Date: 2026-06-24 18:56:15.823596

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '887d198373fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_phone', sa.String(length=20), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('threshold_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    # ### end Alembic commands ###
